"""Public facade for LM Studio LabKit."""

from .artifacts import ArtifactSet, write_run_artifacts
from .benchmarks import (
    BenchmarkConfig,
    BenchmarkSafetyConfig,
    FakeTransport,
    MatrixCell,
    MatrixPlan,
    MatrixTransport,
    ModelSpec,
    StructuredRuntimeConfig,
    TaskSpec,
    plan_matrix,
    run_live_small_text_screening,
    run_matrix,
)
from .datasets import TaskManifest, load_task_manifest, load_task_manifests, load_task_specs
from .live_bridge import LiveBridgeTransport
from .managed_executor import (
    LocalLMStudioHostRunner,
    ManagedExecutionResult,
    ManagedExecutorError,
    ManagedHostRunner,
    ManagedLMStudioExecutor,
    ManagedLMStudioTransport,
)
from .output_budget import (
    AdaptiveOutputBudgetPolicy,
    OutputBudgetDecision,
    OutputBudgetObservation,
    decide_output_budget,
    observe_output_budget,
)
from .requests import (
    ChatMessage,
    ExecutionOptions,
    ImageInput,
    LanguagePolicy,
    RequestEnvelope,
    RequestPlan,
    RequestResult,
    ResponseContract,
    TextInput,
)
from .review_pack import export_review_pack
from .schema_builders import build_blocks_schema, build_simple_flat_schema
from .snapshots import export_latest_text_remote_snapshot
from .validation import (
    ValidationResult,
    ValidationSummary,
    collect_ids_by_path,
    validate_filler_cleanup,
    validate_language,
    validate_paragraphing_metrics,
    validate_punctuation_metrics,
    validate_response,
    validate_term_normalization,
)

__all__ = [
    "AdaptiveOutputBudgetPolicy",
    "ArtifactSet",
    "BenchmarkConfig",
    "BenchmarkSafetyConfig",
    "ChatMessage",
    "ExecutionOptions",
    "FakeTransport",
    "ImageInput",
    "LanguagePolicy",
    "LiveBridgeTransport",
    "LocalLMStudioHostRunner",
    "ManagedExecutionResult",
    "ManagedExecutorError",
    "ManagedHostRunner",
    "ManagedLMStudioExecutor",
    "ManagedLMStudioTransport",
    "MatrixCell",
    "MatrixPlan",
    "MatrixTransport",
    "ModelSpec",
    "OutputBudgetDecision",
    "OutputBudgetObservation",
    "RequestEnvelope",
    "RequestPlan",
    "RequestResult",
    "ResponseContract",
    "StructuredRuntimeConfig",
    "TaskManifest",
    "TaskSpec",
    "TextInput",
    "ValidationResult",
    "ValidationSummary",
    "build_blocks_schema",
    "build_simple_flat_schema",
    "collect_ids_by_path",
    "decide_output_budget",
    "export_review_pack",
    "export_latest_text_remote_snapshot",
    "load_task_manifest",
    "load_task_manifests",
    "load_task_specs",
    "observe_output_budget",
    "plan_matrix",
    "run_live_small_text_screening",
    "run_matrix",
    "validate_filler_cleanup",
    "validate_paragraphing_metrics",
    "validate_punctuation_metrics",
    "validate_term_normalization",
    "validate_language",
    "validate_response",
    "write_run_artifacts",
]
