"""Registry-facing identity contracts."""

# ruff: noqa: I001

from .api_models import (
    LoadedInstanceRecord,
    ModelListRequest,
    ModelListResponse,
    NativeModelFacts,
    VisibleModelRecord,
    parse_compat_model_list,
    parse_native_model_list,
)
from .candidate_execution import (
    CandidateExecutionCatalog,
    CandidateExecutionGateStatus,
    CandidateExecutionRecord,
    L3_8A_GEMMA4_E4B_NO_LIVE_FEASIBILITY_SUMMARY_PATH,
    build_candidate_execution_catalog,
    render_candidate_execution_report,
)
from .candidate_intake import (
    CURRENT_RESPONSES_LONG_CONTEXT_EVIDENCE_BUILD,
    CandidateContextTestPlan,
    CandidateContextTierPlan,
    CandidateEvidencePolicy,
    CandidateHardwareFeasibility,
    CandidateModelIntake,
    CandidateModelIntakeCatalog,
    CandidateModelStatus,
    CandidateRouteStatuses,
    CandidateTestMatrixPlan,
    DeferredModelNotice,
    EvidenceScopedRouteGate,
    build_candidate_hardware_feasibility,
    build_candidate_model_intake_catalog,
    get_candidate_model_intake,
    resolve_openai_responses_long_context_status,
)
from .identity import ModelIdentityFacts
from .models import (
    ModelCandidate,
    ModelCapability,
    ModelEvidenceRef,
    ModelIdentity,
    ModelProfileRecommendation,
    ModelVerificationStatus,
    ProfilePurpose,
    ProfileStatus,
)
from .profiles import (
    LongContextStatus,
    ModelRegistryCatalog,
    ModelRegistryProfile,
    ModelRegistryProfileStatus,
    ParameterClass,
    PrivacyStatus,
    ResponsesRouteStatus,
    build_initial_model_registry,
    get_model_profile,
    responses_long_context_status_for,
    responses_small_context_status_for,
)
from .recommendations import (
    INTERNAL_RECOMMENDATION_DRAFT_SUMMARY_PATH,
    OPENAI_RESPONSES_CURRENT_LONG_CONTEXT_SCOPE,
    OPENAI_RESPONSES_FUTURE_RETEST_SCOPE,
    OPENAI_RESPONSES_SMALL_CONTEXT_SCOPE,
    InternalModelRecommendation,
    InternalRecommendationDraft,
    InternalRecommendationStatus,
    InternalRouteGuidance,
    RecommendationAudience,
    RecommendationScopeGuidance,
    build_internal_recommendation_draft,
    is_safe_for_user_facing_recommendation,
    recommendation_for_model,
    render_internal_recommendation_draft_report,
    route_guidance_for,
)
from .structured_matrix import (
    StructuredJsonGateStatus,
    StructuredJsonMatrixRow,
    StructuredJsonValidationMatrix,
    build_structured_json_validation_matrix,
    get_structured_json_matrix_row,
    render_structured_json_validation_matrix_report,
)

RegistryModelIdentityFacts = ModelIdentityFacts

__all__ = [
    "CURRENT_RESPONSES_LONG_CONTEXT_EVIDENCE_BUILD",
    "CandidateContextTestPlan",
    "CandidateContextTierPlan",
    "CandidateExecutionCatalog",
    "CandidateExecutionGateStatus",
    "CandidateExecutionRecord",
    "CandidateEvidencePolicy",
    "CandidateHardwareFeasibility",
    "CandidateModelIntake",
    "CandidateModelIntakeCatalog",
    "CandidateModelStatus",
    "CandidateRouteStatuses",
    "CandidateTestMatrixPlan",
    "DeferredModelNotice",
    "EvidenceScopedRouteGate",
    "LongContextStatus",
    "INTERNAL_RECOMMENDATION_DRAFT_SUMMARY_PATH",
    "ModelCandidate",
    "ModelCapability",
    "ModelEvidenceRef",
    "ModelIdentity",
    "ModelIdentityFacts",
    "InternalModelRecommendation",
    "InternalRecommendationDraft",
    "InternalRecommendationStatus",
    "InternalRouteGuidance",
    "ModelListRequest",
    "ModelListResponse",
    "ModelRegistryCatalog",
    "ModelRegistryProfile",
    "ModelRegistryProfileStatus",
    "ModelProfileRecommendation",
    "ModelVerificationStatus",
    "LoadedInstanceRecord",
    "L3_8A_GEMMA4_E4B_NO_LIVE_FEASIBILITY_SUMMARY_PATH",
    "NativeModelFacts",
    "OPENAI_RESPONSES_CURRENT_LONG_CONTEXT_SCOPE",
    "OPENAI_RESPONSES_FUTURE_RETEST_SCOPE",
    "OPENAI_RESPONSES_SMALL_CONTEXT_SCOPE",
    "ParameterClass",
    "ProfilePurpose",
    "ProfileStatus",
    "PrivacyStatus",
    "RecommendationAudience",
    "RecommendationScopeGuidance",
    "ResponsesRouteStatus",
    "RegistryModelIdentityFacts",
    "StructuredJsonGateStatus",
    "StructuredJsonMatrixRow",
    "StructuredJsonValidationMatrix",
    "VisibleModelRecord",
    "build_candidate_execution_catalog",
    "build_initial_model_registry",
    "build_internal_recommendation_draft",
    "build_structured_json_validation_matrix",
    "get_model_profile",
    "get_structured_json_matrix_row",
    "is_safe_for_user_facing_recommendation",
    "parse_compat_model_list",
    "parse_native_model_list",
    "recommendation_for_model",
    "render_candidate_execution_report",
    "render_structured_json_validation_matrix_report",
    "render_internal_recommendation_draft_report",
    "route_guidance_for",
    "responses_long_context_status_for",
    "responses_small_context_status_for",
    "build_candidate_hardware_feasibility",
    "build_candidate_model_intake_catalog",
    "get_candidate_model_intake",
    "resolve_openai_responses_long_context_status",
]
